version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "master"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
